from turtle import *
def flower():
    speed(-1)
    color('orange')
    begin_fill()
    fillcolor('yellow')
    for i in range(40):
        lt(210)
        lt(180)
        circle(40,100)
        lt(180)
        circle(40,100)
    end_fill()
    color('brown')
    begin_fill()
    fillcolor('brown')
    up()
    goto(-49,163)
    down()
    circle(60)
    end_fill()
def stick():
    width(5)
    color('green')
    up()
    goto(-28,0)
    down()
    rt(-70)
    fd(300)
def leaf():
    width(2)
    rt(180)
    up()
    fd(170)
    down()
    color('light green')
    begin_fill()
    fillcolor('light green')
    circle(50,100)
    lt(80)
    circle(50,100)
    end_fill()
def leaf2():
    begin_fill()
    fillcolor('light green')
    rt(20)
    circle(50,100)
    lt(80)
    circle(50,100)
    end_fill()
def main():
    reset()
    flower()
    stick()
    leaf()
    leaf2()
    ht()
if __name__=='__main__':
    main()
    mainloop()
