from turtle import *
import random
from tkinter import messagebox
import time
setup(1350,750)
def sun_sky():
    start=time.time()
    colors=['orange','tomato']
    getscreen()
    title('Scenery')
    bgcolor('light sky blue')
    width(3)
    up()
    goto(-250,200)
    down()
    for i in range(25):
        random.shuffle(colors)
        color(colors[0])
        speed(-1)
        circle(40,100)
        rt(-180)
        up()
        fd(45)
        rt(95)
        fd(50)
        down()
        circle(40,100)
    up()
    goto(200,120)
    rt(-75)
    down()
    width(2)
    color('white')
    fillcolor('white')
    begin_fill()
    fd(-160)
    fd(260)
    circle(50,150)
    circle(50,50)
    for i in range(3):
        rt(100)
        circle(50,100+i*10)
        lt(30)
    rt(150)
    circle(40,136)
    ht()
    end_fill()
    width(3)
    color('black')
    up()
    goto(180,200)
    down()
    rt(140)
    circle(50,70)
    rt(145)
    up()
    goto(180,200)
    down()
    circle(-50,70)
    up()
    goto(270,210)
    down()
    rt(-142)
    circle(50,70)
    rt(147)
    up()
    goto(270,210)
    down()
    circle(-50,70)
    up()
    goto(-650,-100)
    rt(16)
    down()
    color('brown')
    fillcolor('brown')
    fd(-25)
    fd(1345)
    begin_fill()
    for p in range(9):
        lt(120)
        fd(150)
        lt(120)
        fd(150)
        lt(120)
    end_fill()
    color('light green')
    fillcolor('light green')
    begin_fill()
    rt(90)
    fd(250)
    rt(-90)
    fd(1355)
    rt(-90)
    fd(250)
    rt(-90)
    fd(1355)
    end_fill()
    rt(-90)
    up()
    goto(230,-150)
    down()
    color('brown')
    fillcolor('brown')
    begin_fill()
    for i in range(2):
        fd(50)
        lt(90)
        fd(10)
        lt(90)
    end_fill()
    up()
    goto(215,-142)
    down()
    color('forest green')
    fillcolor('forest green')
    begin_fill()
    for c in range(6):
        circle(10,180)
        rt(180)
        circle(10,180)
        rt(120)
    end_fill()
    end=time.time()
    d=end-start
    title('Scenery completed in '+str(d)+' seconds')
    messagebox.showinfo('Execution Time',f"Runtime of the program is {end - start} seconds")
def main():
    reset()
    sun_sky()
    ht()
if __name__=='__main__':
    main()
    mainloop()
